---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/ansible"
  KUBERNETES_DIR: "{{.PROJECT_DIR}}/kubernetes"
  TERRAFORM_DIR: "{{.PROJECT_DIR}}/terraform"
  VENV_PATH: "{{.PROJECT_DIR}}/.venv"
  _PYTHON: "{{.VENV_PATH}}/bin/python"


env:
  KUBECONFIG: "{{.PROJECT_DIR}}/kubeconfig"

includes:
  ansible: .taskfiles/Ansible/Taskfile.yaml
  cluster: .taskfiles/ClusterTasks.yml

tasks:

  init:
    desc: Initialize workstation dependencies with Brew
    cmds:
      - task: venv:init
      - task: precommit:init
      - brew install {{.DEPS}} {{.CLI_ARGS}}
    preconditions:
      - sh: command -v brew
        msg: |
          Homebrew is not installed. Using MacOS, Linux or WSL?
          Head over to https://brew.sh to get up and running.
    vars:
      DEPS: >-
        age
        direnv
        fluxcd/tap/flux
        helm
        ipcalc
        jq
        kubectl
        kustomize
        sops
        hashicorp/tap/terraform
        tflint
        yq
        cmctl
