---
k3s_control_node: true
k3s_server:
  cluster-cidr: 10.20.0.0/16
  disable: ["flannel", "local-storage", "metrics-server", "servicelb", "traefik"]
  disable-cloud-controller: true
  disable-kube-proxy: true
  disable-network-policy: true
  docker: false
  flannel-backend: "none" # quote
  kube-controller-manager-arg: ["bind-address=0.0.0.0"]
  kube-scheduler-arg: ["bind-address=0.0.0.0"]
  kubelet-arg: ["image-gc-low-threshold=50", "image-gc-high-threshold=55"]
  node-ip: 10.0.1.4
  secrets-encryption: false
  service-cidr: 10.21.0.0/16
  tls-san: ["10.0.1.4"]
  write-kubeconfig-mode: "0644" # quote
