apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: default,networking,cert-manager,kube-system,media
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:L0awRrOkne0=,iv:d2mHXf58S+SwPdEfsuBgADWVKEIUgZSqCk5c0pClKXY=,tag:VL4UkudZSZM2rvgi4m3oeA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zukJsaKNSeywpegJdR6pB/h65+rKELSU,iv:s1V2ezjWjf61XXjz2Egn4VaCbvkMCjacGAHox0f+24s=,tag:ONO43rGX/mdiGGY3H3Ezmw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:y8bzAJMrSntPgVqULGoegEZfGLm/+6oTwgoHD2GtuDgF7/aMQA==,iv:MP7bhXuuLvwaQAMNjUj58Lm/wMmEAKFK1dK6YNQT9kQ=,tag:ypA3m4bbvhBi3Idvq3JQaw==,type:str]
    CLOUDFLARE_DDNS_RECORD: ENC[AES256_GCM,data:aNEq8FZ8dCEPaQ==,iv:6cAFlsLWq1VTo8DukyF3C23DwFDlr9ZZdLD/eLZ34Jk=,tag:NG0WBOWkatUQwa/ogRAnRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kafyrfhgzqu734zkma2z7tvgq0acylaxylmurlgen77306usqghs254h8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZmRNRGEySmNDQ2laVUI5
            QnZ4TitGamdzb1kyWit5T3lXVlNrOFluMmpZCmlrUVFtZFhja2tUUms3ZWRsZWxK
            NWFHZjFUV2dOeGJHUnVaaXcyZkdEWmMKLS0tIHFhKzVUcFB1ZEF2aE5wdFoyeTMx
            WThwcEE3aXNQaEhYR2JZL0JwbXM3Z00KyB+orqMAtXHzi/Ofyd2cWxMBvlLACe6m
            pusocYzqvTCDIpy+dvWKUVwbbwiEruKVypaatk7vjHlFwBEdujEkRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-07T18:12:01Z"
    mac: ENC[AES256_GCM,data:A+dcY6VFuKHKitw95SRLmFdzxrtSn5kSlKRPc1wZhVvJ7yA/MCZ0H8nSAKGs9l5ezdh93+Z8CRjPjA//TN0nSbmsC6l23TGJTVHzaNGT+inpPqRGeYloqXk1b8k1oLOftipMFU75O9uQ3EkWv4y0JKRrJVROosSTOh1kXGUsBv8=,iv:Hyqdu0KdfY5cNSRWatAnhmoYt8qWJa2nuIUVc6Sb27M=,tag:ykesW5IAes0IRG/Zw0xYPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
